---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- name: for RedHat
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: for Debian
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: acl.yml
- include_tasks: configuration.yml
